In [2]:
import numpy as np
import random
#random.seed(20)

In [3]:
centres = np.array([
    [-1,-1],
    [-1,1],
    [1,1],
    [1,-1]
])
N = centres.shape[0]
location =np.array( [0.5, -0.2])


distantion = np.zeros(N)
for i in range(N):
    distantion[i] = ((location[0] - centres[i,0])**2 +(location[1] - centres[i,1])**2)**0.5


print(distantion)


[1.7        1.92093727 1.3        0.94339811]


In [4]:
def deformation(arr, noise = 0.005):
    random.seed(20)
    for i in range(arr.shape[0]):
        arr[i]+= random.uniform(-noise,noise)
        
deformation(distantion)
distantion

array([1.7040564 , 1.92279981, 1.30266509, 0.94744428])

In [9]:
c_k = np.array([0.1,0.1])
Jf = np.zeros((N, 2))
F = np.zeros(N)

count =0
while count < 200:
    for i in range(N):
        F[i] = c_k[0]**2 +c_k[1]**2 - 2*centres[i,0]*c_k[0] - 2*centres[i,1]*c_k[1] +centres[i,0]**2\
       +centres[i,1]**2 - distantion[i]**2

        Jf[i] = [2*c_k[0]-2*centres[i,0],2*c_k[1]-2*centres[i,1]]
    #Left = np.dot(np.transpose(Jf), Jf)
    #Right = np.dot(np.dot(np.transpose(Jf), Jf), c_k) - np.dot(np.transpose(Jf), F)
    
    #c_k = np.linalg.solve(Left,Right)
    c_k = c_k - np.dot( np.dot(np.linalg.inv(np.dot(np.transpose(Jf), Jf)), np.transpose(Jf)),F)
    count+=1
        
c_k

array([ 0.50244227, -0.1997334 ])